### ISSUE TITLE
Just Straight up jewed sync leak

### ISSUE THREAD

**Issue by Skillnoob** [kisman2000/BaseBand-Leak#2]

**Comment by Taxionic** [comment]
Sync Skid ?????????????? 😳

**Comment by 0x7DB** [comment]
oh goddamnit, if i knew he was gonna just copy the sync leak, i would've made something custom for him to leak ;-;

**Comment by kisman2000** [comment]
> oh goddamnit, if i knew he was gonna just copy the sync leak, i would've made something custom for him to leak ;-;

its just jk

**Comment by kisman2000** [comment]
> Sync Skid ?????????????? 😳

real
